### ISSUE TITLE
Manage cache through DokuWiki integrated one.

### ISSUE THREAD

**Issue by Maesto** [CameronWard301/ytembed#3]
Through the [parser_cache_use](https://www.dokuwiki.org/devel:event:parser_cache_use) event it is possible to handle the updating of the cache through DokuWiki's integrated one. Storing the last time it was updated in the pages metadata and comparing it with the cache's configured lifespan would open up synergies with #1 (No need to update on pageview if the cache is regularly updated by cron)

**Comment by CameronWard301** [comment]
#14 Implements Dokuwiki caching system using the parser_cache_use event
