### ISSUE TITLE
Consider moving caching data to DokuWiki's cachedir

### ISSUE THREAD

**Issue by Maesto** [CameronWard301/ytembed#4]
Through the global $conf variable it's possible to determine the [savedirs](https://www.dokuwiki.org/config:savedir) this includes the path to the cachedir. Consider moving the plugins globally used data cache to data/cache/plugin_ytembed/

It could be useful to implement the global caching for this plugin through a helper plugin? If the YT API allows it, a per page cache would be enough though.

**Comment by CameronWard301** [comment]
Fixed on latest master branch,
