### ISSUE TITLE
[feature request]  Implement privacy feature.

### ISSUE THREAD

**Issue by Maesto** [CameronWard301/ytembed#5]
It would be of great help (not only for the wintergatan wiki) if the plugin could show a locally served YT thumbnail of the Video instead of the embed itself, until a user actually clicks on it. Presenting the user with a (configurable) info that this loads a embed. (Optionally storing this decision in a cookie)

This would enable a Wiki without annoying cookie banners all the while providing great privacy.

**Comment by CameronWard301** [comment]
@Maesto Would it be best to use an action to check to see if they have an "accepted embeds" cookie. If they don't then substitute the iframe with the thumbnail and message?

**Comment by Eskaan** [comment]
@CameronWard301 Coded a simple solution :)
Sadly, I couldnt test the PHP code since my local webserver broke whit the last update (like whit every update before - thanks, apple :frowning: ) but I think it should work.
Also added a simple Style trying to fit whit the wiki ;)
```php
<?php
private function renderYouTubeVideo($request, $parameters): string {
    $embedded = '<iframe style="border: none;" width="'.$parameters["width"].'" height="'.$parameters["height"].'" src="'.$request.'"></iframe>';
    if (!isset($_COOKIE['externalAccepted']){
        $divStyle = 'style="width: 600px;height: 200px;background-color: #0003;text-align: center;padding-top:20px;"';
        if (isset($parameters["height"] && isset($parameters["width"])){
            $divStyle = 'style="width: '.$parameters["width"].'px;height: '.$parameters["height"].'px;background-color: #0003;text-align: center;padding-top:20px;"';
        }
        return '
        <div '.$divStyle.'">
            <button onclick="document.cookie = \'externalAccepted=true\';this.parentElement.outerHTML = ' . $embedded . ';">Accept Embeded</button>
            <button onclick="this.parentElement.outerHTML = ' . $embedded . ';">Accept this one</button>
            <button onclick="this.parentElement.outerHTML = '';">Close - Ask again Later</button>
        </div>
        ';
    } elseif ($_COOKIE['externalAccepted'] == 'true'){
        return $embedded;
    }
?>

**Comment by CameronWard301** [comment]
This is a good start!
I couldn't reproduce the same output on my server. I think there's some apostrophe escaping errors to-do with the iframe.
Also this sort of code needs to go in an action component. That way the cookie can be checked on each page load rather than only checking when building the page. I can create this component sometime tomorrow afternoon.
![Capture](https://user-images.githubusercontent.com/38313327/120907625-f97ce400-c65a-11eb-9f91-9a45b880b094.JPG)
@Code-Ac

**Comment by Maesto** [comment]
> @Maesto Would it be best to use an action to check to see if they have an "accepted embeds" cookie. If they don't then substitute the iframe with the thumbnail and message?
I think server side php should only handle creating the required html for frontend JS to do the actual work of storing preferences in cookies and loading the actual embed.

**Comment by CameronWard301** [comment]
#14 Feature Added
